name: Hourly Feature Pipeline

on:
  schedule:
    - cron: " 0 * * * * "
  workflow_dispatch:

env:
  OPENWEATHER_API_KEY = ${{ scerets.OPENWEATHER_API_KEY}}
  OPENWEATHER_AIR_URL: ${{ secrets.OPENWEATHER_AIR_URL }}
  OPENWEATHER_BASE_URL: ${{ secrets.OPENWEATHER_BASE_URL }}
  HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
  HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
  KARACHI_LAT: ${{ secrets.KARACHI_LAT }}
  KARACHI_LON: ${{ secrets.KARACHI_LON }}
  TMPDIR: "C:/tmp"

jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: set up python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: install dependencies
      run: pip install -r requirements.txt

    - name: run feature pipeline
      run: python src/pipeline_feature.py

